{
    "name": "Yamaha Inventory New",
    "version": "1.0",
	"summary": "Inventory",
    "author": "GMM Yamaha",
    "license": "GPL-3",
    "category": "Inventory",
    "depends": ['stock', 'purchase', 'barcodes',],
    "data": ['data/default_barcode_patterns.xml',
	         'view/stock_move_views.xml',
             'view/purchase_order_views.xml',
             'view/stock_picking_checking_view.xml',
             'wizard/stock_checking_validation_view.xml'],
    'installable': True,
}
