{
    "name": "Stock picking checking",
    "summary": """All pickings per partner validation""",
    "version": "1.0",
	"summary": "Inventory",
    "author": "GMM",
    "license": "GPL-3",
    "category": "Inventory",
    "depends": ['stock', 'purchase', 'barcodes',],
    "data": ['data/default_barcode_patterns.xml',
	         'view/stock_move_views.xml',
             'view/stock_picking_checking_view.xml',
             'view/stock_picking_view.xml',
			 'wizard/stock_checking_validation_view.xml',
			 'wizard/stock_checking_transfer_all_view.xml',
              ],
    'installable': True,
}
